steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'compose'
      - 'up'
      - 'stop'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/scoreboard-poc/mysql-$BRANCH_NAME:$COMMIT_SHA'