version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - "-p ${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/struct.sql:/docker-entrypoint-initdb.d/struct.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
# to get host name for postgres running in container :
# run [docker ps]
# grab "container id" for postgres db
# run [docker inspect <conatainer_id>] then grab the ip adress , that will be the host