apiVersion: v1
kind: Deployment
metadata:
  name: dev-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-postgres
    template:
      metadata:
        containers:
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: postgres-secret-config
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          image: postgres:16
          imagePullPolicy: IfNotPresent
          name: postgres
          ports:
            containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-storage
        labels:
          app: dev-postgres
          spec: null
        volumes:
          name: dev-postgres-storage
          persistentVolumeClaim:
            claimName: dev-postgres-claim
